### 1. What is a Python library? Why ^o we use Python libraries?

### 2. What is the difference between Numpy array and List?

In [2]:
import time
import numpy as np
### creates an array of size 1 lakh elements
A = np.random.randint(100000)
B = np.random.randint(100000)
###now, using time , i will calculate the time difference in computation of dot product of two arrays in this case A and B
initial_time = time.time()
np.dot(A, B)
final_time = time.time()
print("Time taken by numpy arrays to compute dot product :",  str((final_time-initial_time)*1000) + "milliseconds")

Time taken by numpy arrays to compute dot product : 0.3650188446044922milliseconds


### 3. Find the shape, size and dimension of the following array?
### [[1, 2, 3, 4]
### [5, 6, 7, 8],
### [9, 10, 11, 12]]

In [3]:
arr = np.array([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]])
print("size of array means number of elements in array: ",arr.size)

print("Dmensions of array is ", arr.ndim)

print("Shape of array means (number of rows X number of columns)", arr.shape)

size of array means number of elements in array:  12
Dmensions of array is  2
Shape of array means (number of rows X number of columns) (3, 4)


### 4. Write python co^e to access the first row of the following array?
### [[1, 2, 3, 4]
### [5, 6, 7, 8],
### [9, 10, 11, 12]]

In [4]:
### Here array indexing and slicing concept works
arr = np.array([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]])
print("First row can be accessed in this way:" ,arr[0:1, 0:4])   ## only using slicing of array
### arr[rows, columns]
print("First row can be accessed in another way", arr[[0], 0:4])   ### slicing and selecting both

First row can be accessed in this way: [[1 2 3 4]]
First row can be accessed in another way [[1 2 3 4]]


### 5. How ^o you access the element at the thir^ row an^ fourth column from the given numpy array?
### [[1, 2, 3, 4]
### [5, 6, 7, 8],
### [9, 10, 11, 12]]

In [5]:
arr = np.array([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]])

## to access the third row and fourth colummn element , we can use following menthods
print("Element at third row and 4rd col to be:", arr[2][3])  ### it returns an element (scalar)

print("Element at third row and 4rd col to be:", arr[2:3, 3:4])  ## it returns an array 


Element at third row and 4rd col to be: 12
Element at third row and 4rd col to be: [[12]]


### 6. Write code to extract all odd indexed elements from the given numpy array?
### [[1, 2, 3, 4]
### [5, 6, 7, 8],
### [9, 10, 11, 12]]

In [44]:
import numpy as np

# Given NumPy array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Extracting all odd-indexed elements
odd_indexed_elements = arr[:, 1::2]  # Slicing along the second axis (columns) with step size 2

print("Odd-indexed elements:")
print(odd_indexed_elements)


Odd-indexed elements:
[[ 2  4]
 [ 6  8]
 [10 12]]


### 7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [7]:
### We can generate random 3X3 matrix using random module in numpy
## Random values in a given shape.

arr = np.matrix(np.random.rand(3,3))
arr

matrix([[0.0954683 , 0.32955267, 0.57418285],
        [0.25548515, 0.45379067, 0.08033365],
        [0.30855863, 0.56109131, 0.71436426]])

### 8. Describe the difference between np.random.rand and np.random.randn?

In [8]:
# Random values in a given shape.
# Create an array of the given shape and populate it with random samples from a uniform distribution over ``[0, 1)``.
### Parameters
## ----------
## d0, d1, ..., dn : int, optional
    # The dimensions of the returned array, must be non-negative.
    # If no argument is given a single Python float is returned.

arr1 = np.random.rand(3,2)

#randn(d0, d1, ..., dn)
# Return a sample (or samples) from the "standard normal" distribution.

arr2 = np.random.randn(3,2)

print("Array using rand", arr1)
print("Array using randn", arr2)

Array using rand [[0.3594106  0.48445872]
 [0.17369749 0.41671446]
 [0.56177493 0.22130305]]
Array using randn [[-0.43306598 -1.20501897]
 [-0.79026197 -1.02027373]
 [-0.15144083 -0.96391535]]


### 9. Write code to increase the dimension of the following array?
### [[1, 2, 3, 4]
### [5, 6, 7, 8],
### [9, 10, 11, 12]]

In [9]:
### Here we use expand_dims method to increase dimensions by 1
arr = np.array([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]])

# np.expand_dims(a, axis) . Expand the shape of an array.Insert a new axis that will appear at the `axis` position in the 
# expanded array shape.
print("Row wise expansion")
print(np.expand_dims(arr, axis=0))  ## row wise expansion by 1 dimension

print("\n")
print("Column wise expansion")
print(np.expand_dims(arr, axis=1))    ### column wise expansion

Row wise expansion
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


Column wise expansion
[[[ 1  2  3  4]]

 [[ 5  6  7  8]]

 [[ 9 10 11 12]]]


### 10. How to transpose the following array in NumPy?
### [[1, 2, 3, 4]
### [5, 6, 7, 8],
### [9, 10, 11, 12]]

In [10]:
### transpose means simply interchanging the rows and columns....(arr[i][j] = arr[j][i])
### we can use direct attribute availabe in numpy to take transpose
arr = np.array([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]])   ## 3X4 array
arr.T    ### 4X3 array



array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

### 11. Consider the following matrix:
### Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
### Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
### Perform the following operation using Python1
### 1. Index wiLe multiplication
### 2. Matix multiplication
### 3. Add both the matices
### 4. Subtact matrix B from A
### 5. Diide Matrix B by A

In [26]:
mat1 = np.matrix([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
mat2 = np.matrix([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print("Matrix A is ")
print(mat1)
print(" ")
print("matrix B is")
print(mat2)

print("Matrix multiplication is:")
print(np.matmul(mat1, mat2.T))
print("")

print("Sum of matrix is ")
print(mat1 + mat2)
print(" ")

print("Subtraction of matrix is: ")
print(mat1 - mat2)

print("Division of B/A")
print(mat2 / mat1)   ### division only element wise

Matrix A is 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
 
matrix B is
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Matrix multiplication is:
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

Sum of matrix is 
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
 
Subtraction of matrix is: 
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Division of B/A
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### 12. Which function in Numpy can be used to swap the byte order of an array?

In [27]:
### In NumPy, you can use the byteswap() function to swap the byte order of an array. This function creates a new array with 
### the byte order swapped, while leaving the original array unchanged.
arr = np.array([[1,2],[3,4]])

swapped_arr = arr.byteswap()

print("Original array is:")
print(arr)
print('')

print("Swapped array is :")
print(swapped_arr)

Original array is:
[[1 2]
 [3 4]]

Swapped array is :
[[16777216 33554432]
 [50331648 67108864]]


### 13. What is the significance of the np.linalg.inv function?

In [36]:
from numpy.linalg import inv
### inv() used to compute the inverse of matrix A and mathematically, inverse of matrix A is adjoint(A) divided by determinant(A)
### It is widely used in solving the system of linear equations.
### consider system of linear equations be represented as A*X = B WHERE A is matrix of coefficients, X is column matrix containing 
### variables to find

arr = np.array([[-1,2,3],[4,-5,6],[7,8,-9]])

inv_arr = inv(arr)
print('Inverse of matrix is :')
print(inv_arr)



Inverse of matrix is :
[[-0.00833333  0.11666667  0.075     ]
 [ 0.21666667 -0.03333333  0.05      ]
 [ 0.18611111  0.06111111 -0.00833333]]


In [42]:
coeff_mat = np.matrix([[-1,2,3],[4,-5,6],[7,8,-9]])
print("Coefficient matrix is:")
print(coeff_mat)
print("")

constant_mat = np.matrix([[1], [2], [3]])
print("Constant b matrix :")
print(constant_mat)
print("")

inv_coeff_mat = inv(coeff_mat)
print("Inverse of coefficient matrix :")
print(inv_coeff_mat)
print("")

## then solution of matrix is stored in [x,y,z] by np.dot(inv(A), B)
solution_mat = np.dot(inv_coeff_mat, constant_mat)
print("Solution of matrix:")
print(solution_mat)


Coefficient matrix is:
[[-1  2  3]
 [ 4 -5  6]
 [ 7  8 -9]]

Constant b matrix :
[[1]
 [2]
 [3]]

Inverse of coefficient matrix :
[[-0.00833333  0.11666667  0.075     ]
 [ 0.21666667 -0.03333333  0.05      ]
 [ 0.18611111  0.06111111 -0.00833333]]

Solution of matrix:
[[0.45      ]
 [0.3       ]
 [0.28333333]]


### 14. What does the np.reshape function do, and how is it used?

In [38]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = np.reshape(arr, (2, 3))
print("Original Array:")
print(arr)
print("Reshaped Array:")
print(reshaped_arr)

Original Array:
[1 2 3 4 5 6]
Reshaped Array:
[[1 2 3]
 [4 5 6]]


### 15. What is broadcasting in Numpy?

In [40]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([1, 2, 3])

result = A + B

print(result)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
