In [1]:
## generate the value from 1 to 5 and give me 20 values from 1 to 5
import numpy as np

In [2]:
np.linspace(1, 4, 20)

array([1.        , 1.15789474, 1.31578947, 1.47368421, 1.63157895,
       1.78947368, 1.94736842, 2.10526316, 2.26315789, 2.42105263,
       2.57894737, 2.73684211, 2.89473684, 3.05263158, 3.21052632,
       3.36842105, 3.52631579, 3.68421053, 3.84210526, 4.        ])

In [3]:
np.logspace(1,5,10, base = 2)   ### give 10 values from 1 to 5 with log of base 2

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [4]:
np.asanyarray(3)

array(3)

In [5]:
arr1 = np.zeros((2,2))
arr1.shape
print(arr1)

[[0. 0.]
 [0. 0.]]


In [6]:
arr2 = np.zeros((3,4))   ### create array of zeros of 3X4
arr2.shape

(3, 4)

In [7]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [8]:
np.__version__

'1.23.5'

In [9]:
np.__doc__

'\nNumPy\n=====\n\nProvides\n  1. An array object of arbitrary homogeneous items\n  2. Fast mathematical operations over arrays\n  3. Linear Algebra, Fourier Transforms, Random Number Generation\n\nHow to use the documentation\n----------------------------\nDocumentation is available in two forms: docstrings provided\nwith the code, and a loose standing reference guide, available from\n`the NumPy homepage <https://numpy.org>`_.\n\nWe recommend exploring the docstrings using\n`IPython <https://ipython.org>`_, an advanced Python shell with\nTAB-completion and introspection capabilities.  See below for further\ninstructions.\n\nThe docstring examples assume that `numpy` has been imported as `np`::\n\n  >>> import numpy as np\n\nCode snippets are indicated by three greater-than signs::\n\n  >>> x = 42\n  >>> x = x + 1\n\nUse the built-in ``help`` function to view a function\'s docstring::\n\n  >>> help(np.sort)\n  ... # doctest: +SKIP\n\nFor some objects, ``np.info(obj)`` may provide addit

In [10]:
#print(np.__doc__)   ### provides all information regarding numpy

In [11]:
l = [1,2,3,4,5]
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

In [12]:
type(arr)

numpy.ndarray

In [13]:
arr.ndim  ## gives number of dimensions of array

1

In [14]:
arr1 = [[1,2,3], [4,5,6]]
mat = np.matrix(arr1)    ### matrix is by default 2 d array thus if we give another
                    ### dimensional array then it will show erroer.

In [15]:
#### more ways to convert to array:-
np.asarray([[1,2], [3,4], [5,6]])


array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
np.asanyarray([[1,2], [5,6], [8,9]])

array([[1, 2],
       [5, 6],
       [8, 9]])

In [17]:
mat

matrix([[1, 2, 3],
        [4, 5, 6]])

In [18]:
### we can pass tuple, list, integer etc anything to array() fns it will 
### convert to array
a = [1,2,3,4]
b = a.copy()
print(np.array(a))
print(np.array(b))
print("After changing the value in b:")
b[0] = 100
print(np.array(a))
print(np.array(b))

[1 2 3 4]
[1 2 3 4]
After changing the value in b:
[1 2 3 4]
[100   2   3   4]


In [19]:
#### difference between shallow copy and deep copy

In [20]:
#### There are multiple ways to generate array:- 
np.fromfunction(lambda i,j : i*j, (3,3), dtype= int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [21]:
arr.size  ## it tells no of elements in array

5

In [22]:
iterable = (i*i for i in range(5))
np.fromiter(iterable, int)  ### creates a new 1d array from iterable object

array([ 0,  1,  4,  9, 16])

In [23]:
np.fromstring("suhani,ajay,anwesha", sep = " ")

C:\Users\disha\AppData\Local\Temp\ipykernel_7232\3223656957.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring("suhani,ajay,anwesha", sep = " ")


array([], dtype=float64)

In [24]:
list(np.arange(0.1, 10.2, 0.1))

[0.1,
 0.2,
 0.30000000000000004,
 0.4,
 0.5,
 0.6,
 0.7000000000000001,
 0.8,
 0.9,
 1.0,
 1.1,
 1.2000000000000002,
 1.3000000000000003,
 1.4000000000000001,
 1.5000000000000002,
 1.6,
 1.7000000000000002,
 1.8000000000000003,
 1.9000000000000001,
 2.0,
 2.1,
 2.2,
 2.3000000000000003,
 2.4000000000000004,
 2.5000000000000004,
 2.6,
 2.7,
 2.8000000000000003,
 2.9000000000000004,
 3.0000000000000004,
 3.1,
 3.2,
 3.3000000000000003,
 3.4000000000000004,
 3.5000000000000004,
 3.6,
 3.7,
 3.8000000000000003,
 3.9000000000000004,
 4.0,
 4.1,
 4.2,
 4.3,
 4.3999999999999995,
 4.5,
 4.6,
 4.7,
 4.8,
 4.9,
 5.0,
 5.1,
 5.2,
 5.3,
 5.4,
 5.5,
 5.6,
 5.7,
 5.8,
 5.9,
 6.0,
 6.1,
 6.2,
 6.3,
 6.4,
 6.5,
 6.6,
 6.7,
 6.8,
 6.9,
 7.0,
 7.1,
 7.2,
 7.3,
 7.4,
 7.5,
 7.6,
 7.7,
 7.8,
 7.9,
 8.0,
 8.1,
 8.2,
 8.3,
 8.4,
 8.5,
 8.6,
 8.7,
 8.8,
 8.9,
 9.0,
 9.1,
 9.2,
 9.3,
 9.4,
 9.5,
 9.6,
 9.700000000000001,
 9.8,
 9.9,
 10.0,
 10.1]

In [25]:
### Why numpy arrays are preferred than python lists?? ### interview question
# For matrices, the dot product represents a more generalized operation. If A is an m×n matrix and B is an  n×p matrix, 
# the dot product (matrix multiplication) results in an m×p matrix. In NumPy, this can be computed using the np.dot function or
# the @ operator for matrix multiplication.

# For two vectors, A and B, with elements A[0], A[1], ..., A[n-1] and B[0], B[1], ..., B[n-1], the dot product (also known as 
# the inner product or scalar product) is calculated as follows:

# dot product=A[0]×B[0]+A[1]×B[1]+…+A[n−1]×B[n−1]

In [26]:
import numpy as np

# Example matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Using np.dot for matrix multiplication
matrix_product = np.dot(A, B)
print("Matrix product using np.dot:\n", matrix_product)

# Using @ operator for matrix multiplication (Python 3.5 and later)
matrix_product = A @ B
print("Matrix product using @ operator:\n", matrix_product)


Matrix product using np.dot:
 [[19 22]
 [43 50]]
Matrix product using @ operator:
 [[19 22]
 [43 50]]


In [27]:
import numpy as np
import time

# Generate two random NumPy arrays with one million elements each
array1 = np.random.rand(1000000)
array2 = np.random.rand(1000000)

# Measure time for the vectorized version using np.dot
start_time_vectorized = time.time()
result_vectorized = np.dot(array1, array2)
end_time_vectorized = time.time()

# Print the time taken for the vectorized version
print("Time taken for vectorized calculation: " + str(1000 * (end_time_vectorized - start_time_vectorized)) + " milliseconds")

# Reset result_vectorized to 0
result_vectorized = 0

# Measure time for the version using a for loop
start_time_for_loop = time.time()
for index in range(1000000):
    result_vectorized += array1[index] * array2[index]
end_time_for_loop = time.time()

# Print the time taken for the for loop version
print("Time taken for calculation using a for loop: " + str(1000 * (end_time_for_loop - start_time_for_loop)) + " milliseconds")


Time taken for vectorized calculation: 1.0492801666259766 milliseconds
Time taken for calculation using a for loop: 331.5134048461914 milliseconds


In [28]:
np.array(np.matrix([[1, 2], [5, 6]]))


array([[1, 2],
       [5, 6]])

In [29]:
arr = np.array([[1, 2, 3], [4, 5, 6]])


In [30]:
np.count_nonzero(arr)


6

In [31]:
import numpy as geek 
  
my_scalar = 12
   
print ("Input  scalar : ", my_scalar) 
    
out_arr = geek.asanyarray(my_scalar)  
print ("output array from input scalar : ", out_arr)  
print(type(out_arr)) 

Input  scalar :  12
output array from input scalar :  12
<class 'numpy.ndarray'>
