In [1]:
import numpy as np

In [2]:
data = np.array([[1],[2], [3]])

In [3]:
data.ndim

2

In [5]:
a = np.squeeze(data)
a

array([1, 2, 3])

In [6]:
a.ndim

1

In [7]:
### What is the industrial use of np.squeeze()
### it is used in image processing cases and used to squ
#eze array by its one dimension

In [10]:
### repeat
print(data)
np.repeat(data, 4)


[[1]
 [2]
 [3]]


array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [12]:
a = np.array([[1,2], [3,4]])
b = np.repeat(a,2)
### it flattens the data means array of any dim converte
### d into 1 dim array
b

array([1, 1, 2, 2, 3, 3, 4, 4])

In [15]:
b.reshape(2,4)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [16]:
np.repeat(a, 2, axis=1)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [17]:
np.repeat(a, 2, axis=0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [18]:
# Roll array elements along a given axis.
# np.roll(a, shift, axis=None)
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.roll(a, 2)

array([[8, 9, 1],
       [2, 3, 4],
       [5, 6, 7]])

In [21]:
b = [1,2,3,4]
np.roll(b,1)
### it is used to shift the data without losing data

array([4, 1, 2, 3])

In [22]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [23]:
np.roll(b, -1)

array([2, 3, 4, 1])

In [24]:
### we prefer shift operation in pandas than roll functi
###-on in numpy. roll() preserves the data while shift 

### Binary Operations on array:-


In [29]:
arr1 = np.random.randint(1, 10, (3,4))
arr2 = np.random.randint(1, 10, (3, 4))
arr1

array([[9, 9, 1, 2],
       [3, 8, 9, 8],
       [5, 6, 7, 5]])

In [30]:
arr2

array([[7, 5, 8, 8],
       [7, 2, 2, 8],
       [5, 7, 2, 9]])

In [31]:
arr1 + arr2

array([[16, 14,  9, 10],
       [10, 10, 11, 16],
       [10, 13,  9, 14]])

In [32]:
arr1*arr2

array([[63, 45,  8, 16],
       [21, 16, 18, 64],
       [25, 42, 14, 45]])

In [33]:
arr1-arr2

array([[ 2,  4, -7, -6],
       [-4,  6,  7,  0],
       [ 0, -1,  5, -4]])

In [34]:
arr1/arr2

array([[1.28571429, 1.8       , 0.125     , 0.25      ],
       [0.42857143, 4.        , 4.5       , 1.        ],
       [1.        , 0.85714286, 3.5       , 0.55555556]])

In [35]:
arr1 ** arr2

array([[ 4782969,    59049,        1,      256],
       [    2187,       64,       81, 16777216],
       [    3125,   279936,       49,  1953125]])

In [36]:
arr1 > arr2

array([[ True,  True, False, False],
       [False,  True,  True, False],
       [False, False,  True, False]])

In [38]:
~arr1  ### bitwise negation operator

array([[-10, -10,  -2,  -3],
       [ -4,  -9, -10,  -9],
       [ -6,  -7,  -8,  -6]])

In [39]:
arr1

array([[9, 9, 1, 2],
       [3, 8, 9, 8],
       [5, 6, 7, 5]])

In [40]:
arr2

array([[7, 5, 8, 8],
       [7, 2, 2, 8],
       [5, 7, 2, 9]])

In [41]:
arr1**arr2

array([[ 4782969,    59049,        1,      256],
       [    2187,       64,       81, 16777216],
       [    3125,   279936,       49,  1953125]])

#### Numpy string function

In [42]:
arr = np.array(["pw", "skills"])
arr

array(['pw', 'skills'], dtype='<U6')

In [44]:
np.char.upper(arr)  ### returns array with all letters 
 ### to uppercase

array(['PW', 'SKILLS'], dtype='<U6')

In [46]:
np.char.upper(np.array(["ajay"]))

array(['AJAY'], dtype='<U4')

In [47]:
np.char.capitalize(arr)

array(['Pw', 'Skills'], dtype='<U6')

In [48]:
### similar types of opeerations of string in python can
### be done here using char module

In [49]:
np.char.title(arr)

array(['Pw', 'Skills'], dtype='<U6')

#### Mathematical functions

In [50]:
arr1

array([[9, 9, 1, 2],
       [3, 8, 9, 8],
       [5, 6, 7, 5]])

In [51]:
np.sin(arr1)

array([[ 0.41211849,  0.41211849,  0.84147098,  0.90929743],
       [ 0.14112001,  0.98935825,  0.41211849,  0.98935825],
       [-0.95892427, -0.2794155 ,  0.6569866 , -0.95892427]])

In [52]:
np.cos(arr1)

array([[-0.91113026, -0.91113026,  0.54030231, -0.41614684],
       [-0.9899925 , -0.14550003, -0.91113026, -0.14550003],
       [ 0.28366219,  0.96017029,  0.75390225,  0.28366219]])

In [53]:
np.tan(arr1)

array([[-0.45231566, -0.45231566,  1.55740772, -2.18503986],
       [-0.14254654, -6.79971146, -0.45231566, -6.79971146],
       [-3.38051501, -0.29100619,  0.87144798, -3.38051501]])

In [54]:
np.log10(arr1)

array([[0.95424251, 0.95424251, 0.        , 0.30103   ],
       [0.47712125, 0.90308999, 0.95424251, 0.90308999],
       [0.69897   , 0.77815125, 0.84509804, 0.69897   ]])

In [55]:
np.exp(arr1)

array([[8.10308393e+03, 8.10308393e+03, 2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 2.98095799e+03, 8.10308393e+03, 2.98095799e+03],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 1.48413159e+02]])

In [56]:
np.power(arr1, 2)

array([[81, 81,  1,  4],
       [ 9, 64, 81, 64],
       [25, 36, 49, 25]], dtype=int32)

In [57]:
np.mean(arr1)

6.0

In [58]:
np.max(arr1)

9

In [59]:
np.std(arr1)

2.70801280154532

In [61]:
np.median(arr1)

6.5

In [65]:
np.subtract(arr1, arr2)

array([[ 2,  4, -7, -6],
       [-4,  6,  7,  0],
       [ 0, -1,  5, -4]])

In [67]:
np.multiply(arr1, arr2)

array([[63, 45,  8, 16],
       [21, 16, 18, 64],
       [25, 42, 14, 45]])

In [70]:
# Returns the element-wise remainder of division.
np.mod(arr1, arr2)

array([[2, 4, 1, 2],
       [3, 0, 1, 0],
       [0, 6, 1, 5]])

In [71]:
np.sqrt(arr1)

array([[3.        , 3.        , 1.        , 1.41421356],
       [1.73205081, 2.82842712, 3.        , 2.82842712],
       [2.23606798, 2.44948974, 2.64575131, 2.23606798]])

In [72]:
np.var(arr1)

7.333333333333333

### Sorting and searching using numpy

In [73]:
arr = np.array([5,6,7,1])
np.sort(arr)

array([1, 5, 6, 7])

In [75]:
#Find indices where elements should be inserted to maintain order.

# Find the indices into a sorted array `a` such that, if the
# corresponding elements in `v` were inserted before the indices, the
# order of `a` would be preserved.


np.searchsorted(arr, 3)

0

In [76]:
arr1 = np.array([0,1,2,3,0,4])
np.count_nonzero(arr1)

4

In [77]:
arr1 > 0

array([False,  True,  True,  True, False,  True])

In [78]:
np.where(arr1 >0)

(array([1, 2, 3, 5], dtype=int64),)

In [80]:
np.extract(arr1 > 0, arr1)

array([1, 2, 3, 4])

In [81]:
arr1.byteswap()

array([       0, 16777216, 33554432, 50331648,        0, 67108864])

### System of equantions using numpy

In [82]:
import numpy.matlib as nm

In [83]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [85]:
nm.ones((3,4), dtype= int)

matrix([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

### Numpy linear algebra

In [95]:
arr1 = np.random.randint(1,10,(3,3))
arr2 = np.random.randint(1,10,(3,3))

In [96]:
arr1

array([[1, 6, 9],
       [9, 7, 9],
       [3, 3, 5]])

In [97]:
arr2

array([[1, 7, 1],
       [1, 9, 5],
       [5, 5, 3]])

In [98]:
arr1 @ arr2   ### dot product

array([[ 52, 106,  58],
       [ 61, 171,  71],
       [ 31,  73,  33]])

In [104]:
a = np.array([[7,5,-3], [2,-5,2], [5,3,-7]])
b = np.array([16,-8,0])
np.linalg.solve(a, b)

array([1.11304348, 2.85217391, 2.0173913 ])

In [105]:
np.linalg.det(arr1)

-45.999999999999986

In [106]:
np.linalg.det(arr2)

115.99999999999999

In [107]:
np.linalg.inv(arr1)

array([[-0.17391304,  0.06521739,  0.19565217],
       [ 0.39130435,  0.47826087, -1.56521739],
       [-0.13043478, -0.32608696,  1.02173913]])

In [109]:
## np.linalg.cholesky()  ### gives cholesky decompositon

In [110]:
np.linalg.cond(arr1)

37.3979424395434

In [112]:
np.linalg.eig(arr2)

(array([-0.244619  +2.92226102j, -0.244619  -2.92226102j,
        13.48923801+0.j        ]),
 array([[-0.14476267+0.58191856j, -0.14476267-0.58191856j,
         -0.44171282+0.j        ],
        [-0.3193678 -0.16390017j, -0.3193678 +0.16390017j,
         -0.70968691+0.j        ],
        [ 0.71523108+0.j        ,  0.71523108-0.j        ,
         -0.54884813+0.j        ]]))

In [113]:
np.linalg.eigh(arr1)

(array([-5.53487797,  3.32629957, 15.2085784 ]),
 array([[ 0.81820202,  0.16456135,  0.55087659],
        [-0.57059051,  0.34993736,  0.74294705],
        [-0.07051193, -0.92220573,  0.3802166 ]]))