In [1]:
import numpy as np

In [2]:
arr = np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [3]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [5]:
# Return a new array of given shape and type, without initializing entries.

np.empty((3,4), int)

array([[4128860, 6029375, 3801155, 5570652],
       [6619251, 7536754, 6553692, 7536745],
       [6357096, 4259932, 7340144, 6357060]])

In [6]:
np.eye(5)   ##Return a 2-D array with ones on the diagonal and zeros elsewhere.
## always give diagonal matrix so only one parameter is needed

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [7]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [11]:
np.empty((2,2), bool)

array([[ True,  True],
       [ True, False]])

In [12]:
import pandas as pd
pd.DataFrame(arr)

0    1    2    3
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0

In [15]:
import random as rd

In [17]:
rd.choice((1,2,3,4,5,6))  ## Choose a random element from a non-empty sequence.

3

In [19]:
rd.randrange(1, 1000, 9)  ##Choose a random item from range(stop) or range(start, stop[, step]).

190

In [20]:
l = [1,2,3,4,5]
rd.shuffle(l)
l

[3, 1, 2, 4, 5]

In [24]:
rd.uniform(5,10)  ## you will get a number bw 7 and 14
## Get a random number in the range [a, b) or [a, b] depending on rounding.

9.197460984885332

In [25]:
rd.random()  ##random() -> x in the interval [0, 1).

0.31974449711267794

In [26]:
### All above same thing can be done using numpy library
np.random.rand(2,3)  ##Random values in a given shape.

array([[0.88436568, 0.64625211, 0.85995987],
       [0.71875202, 0.391756  , 0.42860019]])

In [27]:
np.random.rand(1)

array([0.28858244])

In [28]:
np.random.randn(2,3)   ##Return a sample (or samples) from the "standard normal" distribution.

array([[-0.13870473,  0.36887769, -0.23016932],
       [ 0.92419358, -1.41744393,  1.44523583]])

In [29]:
np.random.random_sample()
##Return random floats in the half-open interval [0.0, 1.0).

## Results are from the "continuous uniform" distribution over the
## stated interval.  To sample :math:`Unif[a, b), b > a` multiply
## the output of `random_sample` by `(b-a)` and add `a`::

  ## (b - a) * random_sample() + a


0.7695412614143589

In [30]:
np.random.randint(1,5,size= (3,4))   ## generates random integers from 1 to 5 in array
## of dimensions 3X4

array([[3, 3, 3, 4],
       [3, 2, 1, 4],
       [1, 3, 1, 2]])

In [31]:
arr = np.random.randint(1,5,size= (3,4))
arr

array([[4, 2, 3, 4],
       [1, 1, 4, 3],
       [4, 2, 4, 4]])

In [32]:
arr.size

12

In [33]:
arr.ndim

2

In [34]:
arr.shape

(3, 4)

In [35]:
arr.reshape(2,6)

array([[4, 2, 3, 4, 1, 1],
       [4, 3, 4, 2, 4, 4]])

In [36]:
arr.reshape(12,)

array([4, 2, 3, 4, 1, 1, 4, 3, 4, 2, 4, 4])

In [37]:

### when we know only row and not column and have to reshape it in (4X3)
arr.reshape(4,-1)

array([[4, 2, 3],
       [4, 1, 1],
       [4, 3, 4],
       [2, 4, 4]])

In [60]:
arr.reshape(3,-1)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [61]:
arr.reshape(-1,6)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [62]:
arr.reshape(12,1).base   ### it returns our original array
### and thus rehape() gives shallow copy


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [63]:
arr  ### its our original array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [64]:
arr2 = np.array([[2,3], [4,5]])
print(arr2)
print(arr2.ndim)

arr2 = np.zeros((3,4))
print(arr2)
print(arr2.ndim)

[[2 3]
 [4 5]]
2
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2


In [65]:
arr3 = np.zeros((1,3,4))
arr3  ### 3 rows and 4 columns and 1 dimensions

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [66]:
np.ones((1,2,3,4))   ## 3 rows and 4 columns 2 arrays and 1 dimensions

array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]])

In [67]:
arr6 = np.random.randint(1, 10, (5,6))
arr6

array([[2, 6, 3, 2, 7, 6],
       [9, 9, 6, 9, 9, 9],
       [6, 6, 5, 1, 3, 4],
       [2, 6, 9, 8, 4, 5],
       [4, 5, 8, 3, 3, 2]])

In [68]:
arr6 > 7

array([[False, False, False, False, False, False],
       [ True,  True, False,  True,  True,  True],
       [False, False, False, False, False, False],
       [False, False,  True,  True, False, False],
       [False, False,  True, False, False, False]])

In [69]:
arr6[arr6 > 7]  ### to get/filter the values in array greater than 7

array([9, 9, 9, 9, 9, 9, 8, 8])

In [70]:
### we caan access the elements of arr just like list
print(arr6)
print(arr6[0, [1,3]])
print(arr6[0][1:4])
print(arr6[2:5, 2:3])
arr6[2:5, 2:3] = 1000
print(arr6)

[[2 6 3 2 7 6]
 [9 9 6 9 9 9]
 [6 6 5 1 3 4]
 [2 6 9 8 4 5]
 [4 5 8 3 3 2]]
[6 2]
[6 3 2]
[[5]
 [9]
 [8]]
[[   2    6    3    2    7    6]
 [   9    9    6    9    9    9]
 [   6    6 1000    1    3    4]
 [   2    6 1000    8    4    5]
 [   4    5 1000    3    3    2]]


In [71]:
arr6[2:5, [0,2]]

array([[   6, 1000],
       [   2, 1000],
       [   4, 1000]])

In [72]:
arr6[2:5, 0:2]  ### slicing

array([[6, 6],
       [2, 6],
       [4, 5]])

In [73]:
arr6[[2,4], [0,2]]  ### selecting specific rows & cols

array([   6, 1000])

In [74]:
arr6[[2,4], 0:3]    #### selecting and slicing simultaneously

array([[   6,    6, 1000],
       [   4,    5, 1000]])

In [75]:
arr1 = np.random.randint(1,3, (3,3))
arr2 = np.random.randint(1, 3, (3,3))
arr1

array([[2, 2, 1],
       [1, 1, 2],
       [2, 2, 2]])

In [76]:
arr2

array([[1, 2, 1],
       [1, 1, 1],
       [2, 1, 2]])

In [77]:
arr1 + arr2

array([[3, 4, 2],
       [2, 2, 3],
       [4, 3, 4]])

In [78]:
arr1*arr2   ### is not matrx multiplication but index wise simple multiplication

array([[2, 4, 1],
       [1, 1, 2],
       [4, 2, 4]])

In [79]:
arr1-arr2

array([[1, 0, 0],
       [0, 0, 1],
       [0, 1, 0]])

In [80]:
arr1 @ arr2   ### matrix multiplication

array([[6, 7, 6],
       [6, 5, 6],
       [8, 8, 8]])

In [81]:
arr4 = np.dot(arr1, arr2)
arr3 = np.dot(arr2, arr1)

In [82]:
arr3

array([[6, 6, 7],
       [5, 5, 5],
       [9, 9, 8]])

In [83]:
arr4

array([[6, 7, 6],
       [6, 5, 6],
       [8, 8, 8]])

In [84]:
arr5 = arr3 == arr4
arr5

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [85]:
arr1//arr2    ### index wise division

array([[2, 1, 1],
       [1, 1, 2],
       [1, 2, 1]])

In [86]:
arr1/0    ### numpy understands infinity 

C:\Users\disha\AppData\Local\Temp\ipykernel_9688\345804523.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0    ### numpy understands infinity


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

# Broad casting in numpy

In [87]:
## broadcasting means you are applying operations on each of elements of array
arr = np.ones((3,4))
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [88]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [89]:
arr + a   #### now this a is broadcasted to each element row wise

array([[2., 3., 4., 5.],
       [2., 3., 4., 5.],
       [2., 3., 4., 5.]])

In [90]:
##3 to column wise  broadcasting
b = np.array([[1,2,3]])
b.T

array([[1],
       [2],
       [3]])

In [91]:
arr + b.T

array([[2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [92]:
### to square root of arr1
np.sqrt(arr+4)

array([[2.23606798, 2.23606798, 2.23606798, 2.23606798],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [93]:
np.log10(arr)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [94]:
np.exp(arr)

array([[2.71828183, 2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183, 2.71828183]])

In [95]:
np.min(arr1)

1

In [96]:
np.max(arr1)

2

In [97]:
arr.flatten()  ### reduce higher dimension to 1 dimension

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [98]:
## expand_dims
# it expands the array by inserting a new axis(new dimension)
# it is used in image processing
## axis = 1  --> column wise
## axis == 0 --> row wise
arr = np.array([[1,2,3], [4,5,6], [1,2,3]])


In [99]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [100]:
np.sum(arr)

27

In [101]:
### if i want sum only row wise
np.sum(arr, axis = 0)

array([ 6,  9, 12])

In [102]:
np.sum(arr, axis = 1)

array([ 6, 15,  6])

In [103]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [104]:
arr1 = np.expand_dims(arr, axis = 1)
arr1

array([[1],
       [2],
       [3],
       [4]])

In [105]:
arr1.ndim

2

In [106]:
arr2 = np.expand_dims(arr, axis = 0)
arr2

array([[1, 2, 3, 4]])

In [107]:
arr10 = np.zeros((3,4))
arr101 = np.expand_dims(arr10, axis = 0)
arr101

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [108]:
arr11 = np.expand_dims(arr10, axis = 1)
arr11

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])